# Generated by Django 4.2.5 on 2023-09-20 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemType', models.CharField(max_length=100)),
                ('brandName', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField()),
                ('serialNumber', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
    ]
